extends Node

var upgrades := {
	1: {"title": "Advanced Metallurgy", "description": "New alloys for stronger, lighter mechanical parts.", "dependencies": [], "buffs": []},
	2: {"title": "Steam Flow Dynamics", "description": "Mastering steam pressure and flow for stable power.", "dependencies": [], "buffs": []},
	3: {"title": "Engine Efficiency", "description": "Techniques to boost steam engine power and lifespan.", "dependencies": [], "buffs": []},
	4: {"title": "Precision Gearworks", "description": "Fine-tuned gears and cogs for exact control.", "dependencies": [], "buffs": []},
	5: {"title": "Manual Control Systems", "description": "Mechanical systems optimized for hand operation.", "dependencies": [], "buffs": []},
	6: {"title": "Hydraulic Mechanics", "description": "Fluid power for precise mechanical movement.", "dependencies": [], "buffs": []},
	7: {"title": "High-Pressure Boilers", "description": "Managing boilers under extreme steam pressure.", "dependencies": [], "buffs": []},
	8: {"title": "Steam-Powered Optics", "description": "Enhancing manual targeting with steam-driven parts.", "dependencies": [], "buffs": []},
	9: {"title": "Ballistics Optimization", "description": "Improving projectile design for accuracy and power.", "dependencies": [], "buffs": []},
	10: {"title": "Durable Mechanical Design", "description": "Building rugged, wear-resistant machinery.", "dependencies": [], "buffs": []},
	11: {"title": "Material Reinforcement", "description": "Strengthening parts to resist stress and fatigue.", "dependencies": [], "buffs": []},
	12: {"title": "Steam Heat Regulation", "description": "Evenly distributing heat with steam systems.", "dependencies": [], "buffs": []},
	13: {"title": "Condensation Control", "description": "Managing steam condensation for efficiency.", "dependencies": [], "buffs": []},
	14: {"title": "Pressure Regulation Systems", "description": "Manual control of steam pressure and flow.", "dependencies": [], "buffs": []},
	15: {"title": "Integrated Mechanical Systems", "description": "Combining parts for smooth manual operation.", "dependencies": [], "buffs": []},
	16: {"title": "Copper-Enriched Soil Mix", "description": "Copper additives boost soil strength and root health.", "dependencies": [1], "buffs": [{"amount": 5, "type": "yield"}]},
	17: {"title": "Alloy Reinforced Plant Frames", "description": "Brass frames support plants, improving growth stability.", "dependencies": [1], "buffs": [{"amount": 3, "type": "growth speed"}]},
	18: {"title": "Mineral Filtration System", "description": "Filters water with minerals to enrich soil nutrients.", "dependencies": [2], "buffs": [{"amount": 5, "type": "yield"}]},
	19: {"title": "Coal-Powered Radiant Warmers", "description": "Provides steady radiant heat to extend growing periods.", "dependencies": [3], "buffs": [{"amount": 8, "type": "growth speed"}]},
	20: {"title": "Precision Valve Controls", "description": "Hand-operated valves deliver water exactly where needed.", "dependencies": [4], "buffs": [{"amount": 3, "type": "growth speed"}]},
	21: {"title": "Steam-Driven Soil Aerators", "description": "Cranked aerators improve soil oxygen levels manually.", "dependencies": [4], "buffs": [{"amount": 4, "type": "growth speed"}]},
	22: {"title": "Brass-Lined Light Reflectors", "description": "Directs sunlight deep into crop canopies for better yield.", "dependencies": [5], "buffs": [{"amount": 5, "type": "yield"}]},
	23: {"title": "Hand-Cranked Pollination Fans", "description": "Manually operated fans improve pollen distribution.", "dependencies": [5], "buffs": [{"amount": 4, "type": "yield"}]},
	24: {"title": "Copper Ion Soil Treatment", "description": "Releases trace copper ions for stronger plant health.", "dependencies": [5], "buffs": [{"amount": 6, "type": "yield"}]},
	25: {"title": "Steam-Infused Nutrient Feeders", "description": "Pipes distribute nutrients warmed by steam to roots.", "dependencies": [6], "buffs": [{"amount": 7, "type": "growth speed"}]},
	26: {"title": "Condensation Collection Trays", "description": "Collects water vapor for recycling into soil moisture.", "dependencies": [6], "buffs": [{"amount": 5, "type": "growth speed"}]},
	27: {"title": "Thermal Mass Storage Blocks", "description": "Absorbs heat during day, releasing it at night to protect.", "dependencies": [7], "buffs": [{"amount": 5, "type": "growth speed"}]},
	28: {"title": "Steam-Heated Root Warmers", "description": "Pipes keep roots warm during cold conditions.", "dependencies": [7], "buffs": [{"amount": 8, "type": "growth speed"}]},
	29: {"title": "Coal-Warmed Fog Emitters", "description": "Emits warm mist to maintain ideal humidity levels.", "dependencies": [7], "buffs": [{"amount": 6, "type": "growth speed"}]},
	30: {"title": "Manual Seed Sowing Frames", "description": "Cranked seed planters speed sowing without automation.", "dependencies": [8], "buffs": [{"amount": -10, "type": "sowing time"}]},
	31: {"title": "Brass-Coiled Moisture Catcher", "description": "Draws humidity from air to water plants naturally.", "dependencies": [8], "buffs": [{"amount": 5, "type": "growth speed"}]},
	32: {"title": "Precision Soil Gauges", "description": "Brass dials provide soil health data for manual care.", "dependencies": [9], "buffs": [{"amount": 4, "type": "yield"}]},
	33: {"title": "Pressure-Regulated Fertilizer Injector", "description": "Manual pumps control nutrient delivery pressure.", "dependencies": [9], "buffs": [{"amount": 6, "type": "growth speed"}]},
	34: {"title": "Steam-Tuned Soil Panels", "description": "Steam-heated plates prevent soil chill and frost damage.", "dependencies": [10], "buffs": [{"amount": 7, "type": "growth speed"}]},
	35: {"title": "Copper Mesh Growth Frames", "description": "Supports plants and improves airflow for better growth.", "dependencies": [10], "buffs": [{"amount": 4, "type": "growth speed"}]},
	36: {"title": "Heat-Reflective Canopies", "description": "Brass fabric shades block excess heat to prevent wilting.", "dependencies": [11], "buffs": [{"amount": 4, "type": "yield"}]},
	37: {"title": "Manual Irrigation Pumps", "description": "Hand-powered pumps deliver water steadily to crops.", "dependencies": [11], "buffs": [{"amount": 5, "type": "growth speed"}]},
	38: {"title": "Steam-Operated Shade Canopy", "description": "Pulley-driven shades adjust light exposure manually.", "dependencies": [12], "buffs": [{"amount": 4, "type": "yield"}]},
	39: {"title": "Coal-Fired Nutrient Distiller", "description": "Produces nutrient slurry for richer soil feeding.", "dependencies": [12], "buffs": [{"amount": 6, "type": "yield"}]},
	40: {"title": "Brass-Lined Nutrient Channels", "description": "Steam-heated brass pipes deliver enriched nutrients deep to plant roots, boosting vitality.", "dependencies": [13], "buffs": [{"amount": 10, "type": "growth speed"}]},
	41: {"title": "Thermal Regulated Soil Covers", "description": "Insulated soil covers with embedded steam coils maintain stable warmth for continuous root growth.", "dependencies": [13], "buffs": [{"amount": 9, "type": "growth speed"}]},
	42: {"title": "Copper-Infused Soil Panels", "description": "Copper alloy panels regulate soil temperature and emit subtle electromagnetic pulses that enhance plant health.", "dependencies": [14], "buffs": [{"amount": 10, "type": "growth speed"}]},
	43: {"title": "Steam-Humidified Air Chambers", "description": "Enclosed chambers circulate mineral-rich, superheated steam to optimize humidity and accelerate hydration.", "dependencies": [14], "buffs": [{"amount": 12, "type": "growth speed"}]},
	44: {"title": "Coal-Fired Radiant Warmers", "description": "Powerful coal-fueled radiant heaters supply consistent heat, drastically extending growing seasons.", "dependencies": [15], "buffs": [{"amount": 15, "type": "growth speed"}]},
	45: {"title": "Pneumatic Hydraulic Irrigation", "description": "Advanced steam-powered pneumatic pumps deliver water with precise control and high efficiency to all crops.", "dependencies": [15], "buffs": [{"amount": 12, "type": "growth speed"}]},
	46: {"title": "Reinforced Steel Plating", "description": "Stronger hull plating improves tank’s damage resistance.", "dependencies": [1], "buffs": [{"amount": 5, "type": "armor"}]},
	47: {"title": "High-Pressure Steam Engine", "description": "More powerful engine boosts speed and mobility.", "dependencies": [3], "buffs": [{"amount": 7, "type": "speed"}]},
	48: {"title": "Advanced Gear Transmission", "description": "Improved gear systems smooth out handling and speed.", "dependencies": [4], "buffs": [{"amount": 5, "type": "speed"}]},
	49: {"title": "Enhanced Cooling Systems", "description": "Steam cooling prevents overheating under heavy fire.", "dependencies": [7], "buffs": [{"amount": 5, "type": "armor"}]},
	50: {"title": "Precision Targeting Optics", "description": "Brass optics sharpen manual aiming and firing accuracy.", "dependencies": [8], "buffs": [{"amount": 7, "type": "accuracy"}]},
	51: {"title": "Boiler Pressure Stabilizers", "description": "Stabilizes boiler pressure for reliable engine output.", "dependencies": [14], "buffs": [{"amount": 6, "type": "speed"}]},
	52: {"title": "Reinforced Suspension", "description": "Strong suspension improves off-road stability and handling.", "dependencies": [10], "buffs": [{"amount": 5, "type": "speed"}]},
	53: {"title": "Hydraulic Turret Mounts", "description": "Manual hydraulic mounts speed up turret rotation.", "dependencies": [6], "buffs": [{"amount": 6, "type": "turret rotation speed"}]},
	54: {"title": "Coal-Fired Auxiliary Boiler", "description": "Burst steam power boosts engine output temporarily.", "dependencies": [7], "buffs": [{"amount": 8, "type": "speed"}]},
	55: {"title": "Brass-Armored Tracks", "description": "Durable tracks resist damage and improve tank durability.", "dependencies": [10], "buffs": [{"amount": 6, "type": "armor"}]},
	56: {"title": "Smoke Screen Generators", "description": "Creates dense smoke clouds for evasive maneuvers.", "dependencies": [12], "buffs": [{"amount": 5, "type": "accuracy"}]},
	57: {"title": "Manual Ammunition Loader", "description": "Mechanical loader speeds reload without automation.", "dependencies": [5], "buffs": [{"amount": -10, "type": "reload time"}]},
	58: {"title": "Pressure-Regulated Fuel Lines", "description": "Maintains steady fuel flow for consistent engine power.", "dependencies": [14], "buffs": [{"amount": 6, "type": "speed"}]},
	59: {"title": "Reinforced Battle Plating", "description": "Additional armor layers for front-line durability.", "dependencies": [10], "buffs": [{"amount": 10, "type": "armor"}]},
	60: {"title": "Steam-Cooled Gun Barrels", "description": "Keeps barrels cool for sustained firing rate.", "dependencies": [4], "buffs": [{"amount": 8, "type": "weapon damage"}]},
	61: {"title": "Mechanical Targeting Computer", "description": "Gear-driven computing aids manual targeting.", "dependencies": [8], "buffs": [{"amount": 7, "type": "accuracy"}]},
	62: {"title": "Reinforced Boiler Chambers", "description": "Extra protection for boilers against combat damage.", "dependencies": [12], "buffs": [{"amount": 5, "type": "armor"}]},
	63: {"title": "Turbocharged Steam Exhaust", "description": "Optimized exhaust increases engine speed and power.", "dependencies": [9], "buffs": [{"amount": 8, "type": "speed"}]},
	64: {"title": "Armored Driver’s Cockpit", "description": "Reinforced plating protects driver from incoming fire.", "dependencies": [10], "buffs": [{"amount": 6, "type": "armor"}]},
	65: {
	"title": "Juggernaut Siege Systems",
	"description": "Integrated war tech combines power, speed, and protection.",
	"dependencies": [15],
	"buffs": [
		{"amount": 25, "type": "armor"},
		{"amount": 20, "type": "weapon damage"},
		{"amount": 15, "type": "speed"}
	]
}}
